// 音色/视频合成的图片编辑API
import api from "@/utils/request";

/**
 * body参数
 * 公共参数
 * @param {string} model 模型选择  
 * @param {file} images 3选1 上传图片组 示例值: file://C:\Users\lery\Downloads\bg(1).jpg
 * @param {array[string]} image_urls 3选1 上传图片链接组 示例值: ["https://download.mindcraft.com.cn/mindcraft_media/api_file/0027b4a1-6234-474a-ad9f-1a03745043dd.png"]
 * @param {array[string]} image_base64 3选1 上传图片base64组  示例值：["iVBORw0KGgoAAAANSUhEUgAAAeAAAAKqCAYAAADi/40CAAAgAElEQVR4AezBCxxx"]
 * 
 * 图片提取蒙版
 * @param {integer } max_entity 输出mask数量
 * @param {enum<integer>} return_format 对边缘增强 0 （图层的index_map（索引图 1 所有实体图层 (最多max_entity个)）  2 （原图1张 + 图层index_map）  3 （原图1张 + 所有实体图层 (最多max_entity个)）  4 （最大实体图层前景图 + 最大实体图层） 
 * @param {enum<integer>} refine_mask 对边缘增强  0 （不对边缘增强）   1 （对边缘增强） 
 * 
 * 消除图片
 * @param {string} model_quality 图片质量  H（质量最高，速度稍慢） M （质量中等，速度一般） L （质量较低，速度最快） 
 * @param {integer} max_entity 输出mask数量  输出mask数量
 * @param {integer} result_format 对边缘增强  0 （不对边缘增强）   1 （对边缘增强） 
 * @param {integer} seed 图片种子   >= -1 <= 9999999999
 * @param {number} scale 文本影响程度  >= 1 <= 20 （默认值:7） 
 * @param {integer} steps 图片步骤  >= 1 <= 200
 * @param {string} strength 图片控制幅度   >= 0 <= 1 （默认值:0.8） 
 * @param {integer} dilate_size mask 膨胀半径   >= 0 <= 50
 * @param {boolean} add_logo 添加水印  
 * @param {string} position 水印的位置  0 （右下角）  1（ 左下角）  2 （左上角）  3 （右上角） 
 * @param {integer} language 水印的语言   0 （中文（AI生成））  1 （英文（Generated by AI）） 
 * @param {number} opacity 水印不透明度  
 * @param {string} logo_text_content 明水印自定义内容 
 * 
 * 重绘
 * @param {string} prompt 图像的提示词  
 * @param {integer} seed 图片种子   >= -1 <= 9999999999
 * @param {number} scale 文本影响程度  >= 1 <= 20 （默认值:7） 
 * @param {integer} steps 图片步骤  >= 1 <= 200
 * @param {boolean} add_logo 添加水印  
 * @param {string} position 水印的位置  0 （右下角）  1（ 左下角）  2 （左上角）  3 （右上角） 
 * @param {integer} language 水印的语言   0 （中文（AI生成））  1 （英文（Generated by AI）） 
 * @param {number} opacity 水印不透明度  
 * @param {string} logo_text_content 明水印自定义内容 
 * 
 * 扩图
 * @param {integer} result_format 对边缘增强  0 （不对边缘增强）   1 （对边缘增强） 
 * @param {string} prompt 图像的提示词  
 * @param {integer} seed 图片种子   >= -1 <= 9999999999
 * @param {number} scale 文本影响程度  >= 1 <= 20 （默认值:7） 
 * @param {integer} steps 图片步骤  >= 1 <= 200
 * @param {boolean} add_logo 添加水印  
 * @param {string} position 水印的位置  0 （右下角）  1（ 左下角）  2 （左上角）  3 （右上角） 
 * @param {integer} language 水印的语言   0 （中文（AI生成））  1 （英文（Generated by AI）） 
 * @param {number} opacity 水印不透明度  
 * @param {string} logo_text_content 明水印自定义内容 
 * @param {number } top 向上扩展比例 >= 0 <= 1
 * @param {number } left 向左扩展比例 >= 0 <= 1
 * @param {number } bottom 向下扩展比例 >= 0 <= 1
 * @param {number } right 向右扩展比例 >= 0 <= 1
 * @param {number } max_width 最大输出宽度 >= 100 <= 1920
 * @param {number } max_height 最大输出高度 >= 100 <= 1920
*/
export const apiImgToImgMask = (params) => {
  params.noLoading = 1
  return api.post("/v1/images/img2img/mask", params);
}
/**
 *高清图片
 * */
export const apiImgToImgHD = (params) => {
  params.noLoading = 1
  return api.post("/v1/images/img2img", params);
}


/**
 * 获取图生图参数
*/
export const apiImgToImgParams = () => {
  return api.get("/v1/agent/image2image/");
}

/**
 * 图生图
*/
export const apiImgToImg = (params) => {
  params.noLoading = 1
  return api.post("/v1/agent/image2image/", params);
}

